openapi: 3.0.0
info:
  title: 'Tic Tac Toe API'
  version: '0.1'
paths:
  /move:
    post:
      operationId: 'Dykyi\Application\Controllers\TicTacToeController::move'
      parameters:
        -
          name: boardState
          in: query
          description: 'Current board state (JSON format)'
          required: true
          schema:
            type: string
            format: json
            default:
              -
                - ''
                - ''
                - ''
              -
                - ''
                - ''
                - ''
              -
                - ''
                - ''
                - ''
        -
          name: playerUnit
          in: query
          description: 'Player unit representation'
          required: true
          schema:
            type: string
          example: X
      responses:
        '200':
          description: 'Coordinate for the next move'
